version: 0.1
phases:
  install:
    commands:
      - apt-get -y update && apt-get -y upgrade
      - apt-get -y install ssh
      - apt-get -y install jq
      - chmod u+x infrastructure/codebuild/*
      - infrastructure/codebuild/install_terraform.sh
      - infrastructure/codebuild/setup_github_access.sh
      - infrastructure/codebuild/get_ssh_key.sh

  build:
    commands:
        - chmod u+x terraform/shiny_proxy/bin/install_shiny_proxy.sh
        - infrastructure/codebuild/setup_terraform_aws_credentials.sh
        - infrastructure/codebuild/deploy_infra.sh
        - infrastructure/codebuild/clone_repos.sh


