version: 0.2
phases:
  install:
    commands:
      - apt-get -y update && apt-get -y upgrade
      - apt-get -y install jq
      - apt-get -y install software-properties-common
      - add-apt-repository -y ppa:jonathonf/python-3.6
      - apt-get -y update
      - apt-get -y install python3.6
      - apt-get -y update
      - wget https://bootstrap.pypa.io/get-pip.py
      - python3.6 get-pip.py
      - python3.6 -m pip install pyaml cerberus
      - pip3 install awscli
      - chmod u+x infrastructure/codebuild/*
      - infrastructure/codebuild/install_terraform.sh



  build:
    commands:
        - infrastructure/codebuild/setup_terraform_aws_credentials.sh
        - python3.6 infrastructure/codebuild/parse_docker_images.py config/${DeploymentEnvironment}/public_application.yml config/${DeploymentEnvironment}/application.yml
        - infrastructure/codebuild/deploy_infra.sh



