version: 0.2
phases:
  install:
    commands:
      - apt-get -y update && apt-get -y upgrade
      - apt-get -y install ssh
      - apt-get -y install openssh-client
      - apt-get -y install jq
      - apt-get -y install software-properties-common
      - add-apt-repository -y ppa:jonathonf/python-3.6
      - apt-get -y update
      - apt-get -y install python3.6
      - apt-get -y update
      - wget https://bootstrap.pypa.io/get-pip.py
      - python3.6 get-pip.py
      - python3.6 -m pip install pyaml cerberus
      - chmod u+x infrastructure/codebuild/*
      - infrastructure/codebuild/install_terraform.sh
      - infrastructure/codebuild/setup_github_access.sh


  build:
    commands:
        - infrastructure/codebuild/setup_terraform_aws_credentials.sh
        - python3.6 infrastructure/codebuild/build_docker_images.py infrastructure/app_images/dev_images.yml
        - chmod u+x infrastructure/terraform/shiny_proxy/bin/install_shiny_proxy.sh
        - infrastructure/codebuild/deploy_infra.sh
        - infrastructure/codebuild/setup_bastion.sh
        #- infrastructure/codebuild/clone_repos.sh
        - infrastructure/codebuild/start_shinyproxy.sh



