version: 0.2
phases:
  install:
    commands:
      - apt-get -y update && apt-get -y upgrade
      - apt-get -y install ssh
      - apt-get -y install openssh-client
      - apt-get -y install jq
      - apt-get -y install software-properties-common
      - add-apt-repository -y ppa:jonathonf/python-3.6
      - apt-get -y update
      - apt-get -y install python3.6
      - apt-get -y update
      - wget https://bootstrap.pypa.io/get-pip.py
      - python3.6 get-pip.py
      - python3.6 -m pip install pyaml cerberus
      - pip3 install awscli
      - chmod u+x infrastructure/codebuild/*
      - infrastructure/codebuild/install_terraform.sh
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:git-core/ppa
      - apt-get update
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - apt-get install -y git-lfs
      - git lfs install

      - infrastructure/codebuild/setup_github_access.sh


  build:
    commands:
        - infrastructure/codebuild/setup_terraform_aws_credentials.sh
        - python3.6 infrastructure/codebuild/build_docker_images.py infrastructure/app_images/dev_images.yml
        - chmod u+x infrastructure/terraform/shiny_proxy/bin/install_shiny_proxy.sh
        - infrastructure/codebuild/deploy_infra.sh



