version: 0.1
phases:
  install:
    commands:
      - apt-get -y update && apt-get -y upgrade
      - apt-get -y install ssh
      - apt-get -y install jq
      - chmod u+x infrastructure/codebuild/*
      - infrastructure/codebuild/install_terraform.sh
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:git-core/ppa
      - apt-get update
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - apt-get install -y git-lfs
      - git lfs install

      - infrastructure/codebuild/setup_github_access.sh
      #- infrastructure/codebuild/get_ssh_key.sh

  build:
    commands:
        - chmod u+x infrastructure/terraform/shiny_proxy/bin/install_shiny_proxy.sh
        - infrastructure/codebuild/setup_terraform_aws_credentials.sh
        - infrastructure/codebuild/deploy_infra.sh
        - infrastructure/codebuild/setup_bastion.sh
        - infrastructure/codebuild/clone_repos.sh
        - infrastructure/codebuild/start_shinyproxy.sh



